### ISSUE TITLE
Only getting null returned

### ISSUE THREAD

**Issue by TheMinefighter** [mjebrahimi/RamDisk#5]
Hi, when I try to mount any virtual disk with this lib (including the unit tests), I just get `null` returned (and no disk). Is there anything I am doing wrong, which is not mentioned in the readme, or is there any way to get a further error description? 

I'm running Windows 10 20.04 and version 1.0.3

**Comment by mjebrahimi** [comment]
Hi, It works for me and I don't know the cause of your problem .

Can you test it with **Run as Administrator**?

This may not work due to a lack of access to OS API.

If it still doesn't work, can you debug the project source and provide more information about your problem?

**Comment by TheMinefighter** [comment]
Ok, seems that when I run it as **commandline** standalone that I get the error
![image](https://user-images.githubusercontent.com/32145868/83953069-a56bd380-a83d-11ea-8a11-6c43fb323bf6.png). Fixed it; everything works. Was just me beeing dumb and having not enough background info. Will write an PR for the readme so that not another idiot like doesn't understand it.
